# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn install # runs during prebuild
    command: yarn start

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

github:
  prebuilds:
    pullRequestsFromForks: true
    addLabel:  prebuilt-in-gitpod